# Generated by Django 3.2 on 2022-05-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Middle_name', models.CharField(max_length=40)),
                ('Last_name', models.CharField(max_length=30)),
                ('Department', models.CharField(max_length=50, null=True)),
                ('Age', models.IntegerField()),
                ('Mob_no', models.IntegerField()),
                ('Emp_id', models.IntegerField()),
                ('position', models.CharField(choices=[('Assistent', 'Assistent'), ('Developer', 'Developer'), ('CEO', 'CEO'), ('Manager', 'Manager')], max_length=20)),
                ('Email_id', models.EmailField(max_length=30)),
                ('current_address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
